//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bang_luong
    {
        public int Ma_bang_luong { get; set; }
        public Nullable<System.DateTime> Thang_tinh_luong { get; set; }
        public Nullable<double> Luong_co_ban { get; set; }
        public Nullable<double> So_gio_lam_them { get; set; }
        public Nullable<double> Phu_cap { get; set; }
        public Nullable<double> Luong_thuc_nhan { get; set; }
        public int Ma_nhan_vien { get; set; }
    
        public virtual Nhan_vien Nhan_vien { get; set; }
    }
}
