//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bang_cap
    {
        public int Ma_bang_cap { get; set; }
        public string Ten_bang_cap { get; set; }
        public string Ten_co_so_giao_duc { get; set; }
        public Nullable<System.DateTime> Ngay_cap_bang { get; set; }
        public string Hang_bang { get; set; }
        public string Chuyen_nganh_dao_tao { get; set; }
        public int Ma_nhan_vien { get; set; }
    
        public virtual Nhan_vien Nhan_vien { get; set; }
    }
}
