//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cham_cong
    {
        public int Ma_cham_cong { get; set; }
        public Nullable<System.DateTime> Ngay_lam_viec { get; set; }
        public Nullable<double> So_gio_lam_viec_trong_ngay { get; set; }
        public int Ma_nhan_vien { get; set; }
        public int Ma_ban_cham_cong { get; set; }
    
        public virtual Nhan_vien Nhan_vien { get; set; }
    }
}
