//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLy_NhanVienEntities : DbContext
    {
        public QuanLy_NhanVienEntities()
            : base("name=QuanLy_NhanVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bang_cap> Bang_cap { get; set; }
        public virtual DbSet<Bang_luong> Bang_luong { get; set; }
        public virtual DbSet<Cham_cong> Cham_cong { get; set; }
        public virtual DbSet<Chuc_vu> Chuc_vu { get; set; }
        public virtual DbSet<Don_xin_thoi_viec> Don_xin_thoi_viec { get; set; }
        public virtual DbSet<Hop_dong> Hop_dong { get; set; }
        public virtual DbSet<Nghi_phep> Nghi_phep { get; set; }
        public virtual DbSet<Nhan_vien> Nhan_vien { get; set; }
        public virtual DbSet<Phong_ban> Phong_ban { get; set; }
        public virtual DbSet<Phu_cap> Phu_cap { get; set; }
        public virtual DbSet<Quyen_han> Quyen_han { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tai_khoan> Tai_khoan { get; set; }
    }
}
