//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhan_vien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhan_vien()
        {
            this.Bang_cap = new HashSet<Bang_cap>();
            this.Bang_luong = new HashSet<Bang_luong>();
            this.Cham_cong = new HashSet<Cham_cong>();
            this.Don_xin_thoi_viec = new HashSet<Don_xin_thoi_viec>();
            this.Hop_dong = new HashSet<Hop_dong>();
            this.Nghi_phep = new HashSet<Nghi_phep>();
            this.Phu_cap = new HashSet<Phu_cap>();
            this.Tai_khoan = new HashSet<Tai_khoan>();
        }
    
        public int Ma_nhan_vien { get; set; }
        public string Ho_va_ten { get; set; }
        public string Gioi_tinh { get; set; }
        public string So_dien_thoai { get; set; }
        public string Ten_chuc_vu { get; set; }
        public Nullable<System.DateTime> Ngay_bat_dau_lam_viec { get; set; }
        public int Ma_phong_ban { get; set; }
        public int Ma_chuc_vu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bang_cap> Bang_cap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bang_luong> Bang_luong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cham_cong> Cham_cong { get; set; }
        public virtual Chuc_vu Chuc_vu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_xin_thoi_viec> Don_xin_thoi_viec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hop_dong> Hop_dong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nghi_phep> Nghi_phep { get; set; }
        public virtual Phong_ban Phong_ban { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phu_cap> Phu_cap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tai_khoan> Tai_khoan { get; set; }
    }
}
