//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phu_cap
    {
        public int Ma_phu_cap { get; set; }
        public string Loai_phu_cap { get; set; }
        public Nullable<double> So_tien_phu_cap { get; set; }
        public int Ma_nhan_vien { get; set; }
    
        public virtual Nhan_vien Nhan_vien { get; set; }
    }
}
