//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tai_khoan
    {
        public int Ma_tai_khoan { get; set; }
        public string Ten_tai_khoan { get; set; }
        public string Mat_khau { get; set; }
        public int Ma_quyen_han { get; set; }
        public Nullable<int> Ma_nhan_vien { get; set; }
    
        public virtual Nhan_vien Nhan_vien { get; set; }
        public virtual Quyen_han Quyen_han { get; set; }
    }
}
